version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - 8000:8000
    environment:
      HTTP_PORT: 8000
      MS_USER_SERVICE_HOST: user-service
      MS_USER_SERVICE_GRPC_PORT: 8000
      MS_NEWS_SERVICE_HOST: news-service
      MS_NEWS_SERVICE_GRPC_PORT: 8000

  user-service:
    build:
      context: ./user-service
    environment:
      GRPC_PORT: 8000

  news-service:
    build:
      context: ./news-service
    environment:
      GRPC_PORT: 8000
